# DOCKER REPO
- name: create docker repo
  uri:
    url: "{{ api_url }}/v1/repositories/docker/hosted"
    method: POST
    body: "{{ docker_repo_request_body }}"
    status_code: "201"
  when: docker_repo_request_body.name not in repo_names
  register: docker_repo_api_response

- name: debug create docker repo
  debug:
    var: docker_repo_api_response
  when: enable_debug_output == "true"
