kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-ingress-config
  namespace: ingress-tls
data:
  # https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#hsts
  hsts-include-subdomains: "false"
  hsts-max-age: "1"
  hsts: "false"
  proxy-connect-timeout:  "3600s"
  proxy-read-timeout: "3600s"
  redirect-to-https: "false"
  ssl-redirect: "false"
