---
# https://argoproj.github.io/argo-cd/user-guide/helm/
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # ! MUST match the existing helm release name
  name: ar-gitlab
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:adamrushuk/charts-private.git
    targetRevision: main
    path: gitlab-https
    helm:
      # target helm version
      version: v3
      # releaseName: ar-gitlab
      valueFiles:
      - ar-values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: gitlab
  syncPolicy: {}
