# https://argoproj.github.io/argo-cd/user-guide/helm/
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # ! MUST match the existing helm release name: https://argoproj.github.io/argo-cd/user-guide/helm/#helm-release-name
  name: ar-gitlab
  # namespace of argo cd deployment
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:adamrushuk/charts-private.git
    targetRevision: main
    path: charts/gitlab-https
    helm:
      # target helm version
      version: v3
      # values file path is relative from the source.path folder
      valueFiles:
        - ar-values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: gitlab
  syncPolicy: {}
    # # sync options which modifies sync behavior
    # syncOptions:
    #   # namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster
    #   - CreateNamespace=true
