apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello
  name: hello
  namespace: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - image: docker-__DNS_DOMAIN_NAME__/hello
        imagePullPolicy: Always
        name: hello
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred
---
  apiVersion: v1
  kind: Service
  metadata:
    name: hello
    labels:
      app: hello
  spec:
    ports:
    - port: 80
    selector:
      app: hello
---
  apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    name: hello
    namespace: hello
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.org/hsts: "false"
  spec:
    rules:
    # http://__DNS_DOMAIN_NAME__/hello
    - host: __DNS_DOMAIN_NAME__
      http:
        paths:
        - backend:
            serviceName: hello
            servicePort: 80
          path: /hello
