# Chocolatey Proxy Repo
- name: create chocolatey proxy repo
  uri:
    url: "{{ api_url }}/v1/repositories/nuget/proxy"
    method: POST
    body: "{{ chocolatey_proxy_repo_request_body }}"
    status_code: "201"
  when: chocolatey_proxy_repo_request_body.name not in repo_names
  register: chocolatey_proxy_repo_api_response

- name: debug create chocolatey proxy repo
  debug:
    var: chocolatey_proxy_repo_api_response
  when: enable_debug_output == "true"
