# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: Build environment

# name of GitHub event that triggers workflow
# https://help.github.com/en/actions/reference/events-that-trigger-workflows#watch-event-watch
on:
  # trigger when I star my own repo
  watch:
    types: [started]
  # trigger via webhook
  # https://github.com/adamrushuk/aks-nexus-velero/blob/master/TriggerCustomAction.ps1#L28
  repository_dispatch:
    types: [terraform-destroy, delete-all]

# global environment variables
# https://help.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables
env:
  # prefix: used for some globally unique name requirements
  PREFIX: rush
  # debug
  CI_DEBUG: true
  # azure creds
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  LOCATION: uksouth
  # STORAGE_KEY: 'env var set by Get-StorageKey.ps1'

jobs:
  build:

    # always pin versions
    runs-on: ubuntu-18.04

    # only run if owner triggered action
    if: github.actor == github.event.repository.owner.login

    env:
      AKS_RG_NAME: ${{ env.PREFIX }}-rg-aks-dev-001
      ACR_NAME: ${{ env.PREFIX }}acr001${{ env.LOCATION }}001
      AKS_CLUSTER_NAME: ${{ env.PREFIX }}-aks-001
      TERRAFORM_STORAGE_ACCOUNT: ${{ env.PREFIX }}sttfstate${{ env.LOCATION }}001
      TERRAFORM_STORAGE_RG: ${{ env.PREFIX }}-rg-tfstate-dev-001

    steps:
    - uses: actions/checkout@v2

    - name: Login to Azure
      run: pwsh -command "./scripts/Login-Azure.ps1"

    - name: Create Storage Account for Terraform state
      run: pwsh -command "./scripts/Create-AzStorage.ps1"

    - name: Lookup Storage Key
      run: pwsh -command "./scripts/Get-StorageKey.ps1"

    - name: Replace tokens in Terraform config files
      run: pwsh -command "./scripts/Replace-Tokens.ps1"

    - name: Terraform Init
      run: pwsh -command "./scripts/Init-Terraform.ps1"

    - name: Terraform Plan
      run: pwsh -command "./scripts/Plan-Terraform.ps1"
      if: github.event.action != 'delete-all'

    - name: Terraform Apply
      run: pwsh -command "./scripts/Apply-Terraform.ps1"
      if: github.event.action != 'delete-all'


    # Kubernetes
    - name: Deploy Ingress Controller
      run: pwsh -command "./scripts/Deploy-Ingress-Controller.ps1"
      if: github.event.action != 'delete-all'


    # Destroy / Delete
    - name: Terraform Destroy
      run: pwsh -command "./scripts/Destroy-Terraform.ps1"
      # if: (github.event.action == 'terraform-destroy') || (github.event.action == 'delete-all')
      if: github.event.action == 'delete-all'

    - name: Delete Storage
      run: pwsh -command "./scripts/Delete-Storage.ps1"
      if: github.event.action == 'delete-all'
