# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: Build environment

# name of GitHub event that triggers workflow
# https://help.github.com/en/actions/reference/events-that-trigger-workflows#watch-event-watch
on:
  watch:
    types: [started]
  # TODO: add custom web hook to trigger builds from IFTTT or similar
  # repository_dispatch:
  #   types: [<custom event action>]



# global environment variables
# https://help.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables
env:
  # prefix: used for some globally unique name requirements
  PREFIX: rush
  # debug
  CI_DEBUG: false
  # azure creds
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  LOCATION: uksouth
jobs:
  build:

    # always pin versions
    runs-on: ubuntu-18.04

    # only run if owner triggered action
    if: github.actor == github.event.repository.owner.login

    steps:
    - uses: actions/checkout@v2

    - name: Login to Azure
      run: pwsh -command "./scripts/Login-Azure.ps1"

    - name: Create Storage Account
      env:
        TERRAFORM_STORAGE_ACCOUNT: ${{ env.PREFIX }}sttfstate${{ env.LOCATION }}001
        TERRAFORM_STORAGE_RG: ${{ env.PREFIX }}-rg-tfstate-dev-001
      run: pwsh -command "./scripts/Create-AzStorage.ps1"
