# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: Build environment

# name of GitHub event that triggers workflow
# https://help.github.com/en/actions/reference/events-that-trigger-workflows#watch-event-watch
on:
  watch:
    types: [started]
  # TODO: add custom web hook to trigger builds from IFTTT or similar
  repository_dispatch:
    types: [terraform-destroy, delete-all]



# global environment variables
# https://help.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables
env:
  # prefix: used for some globally unique name requirements
  PREFIX: rush
  # debug
  CI_DEBUG: true
  # azure creds
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  LOCATION: uksouth

  # STORAGE_KEY: 'env var set by Get-StorageKey.ps1'
jobs:
  build:

    # always pin versions
    runs-on: ubuntu-18.04

    # only run if owner triggered action
    if: github.actor == github.event.repository.owner.login

    steps:
    - uses: actions/checkout@v2

    - name: Login to Azure
      run: pwsh -command "./scripts/Login-Azure.ps1"

    - name: Create Storage Account for Terraform state
      run: pwsh -command "./scripts/Create-AzStorage.ps1"
      env:
        TERRAFORM_STORAGE_ACCOUNT: ${{ env.PREFIX }}sttfstate${{ env.LOCATION }}001
        TERRAFORM_STORAGE_RG: ${{ env.PREFIX }}-rg-tfstate-dev-001

    - name: Lookup Storage Key
      run: pwsh -command "./scripts/Get-StorageKey.ps1"
      env:
        TERRAFORM_STORAGE_ACCOUNT: ${{ env.PREFIX }}sttfstate${{ env.LOCATION }}001
        TERRAFORM_STORAGE_RG: ${{ env.PREFIX }}-rg-tfstate-dev-001

    - name: Replace tokens in Terraform config files
      run: pwsh -command "./scripts/Replace-Tokens.ps1"
      env:
        AKS_RG_NAME: ${{ env.PREFIX }}-rg-aks-dev-001
        ACR_NAME: ${{ env.PREFIX }}acr001${{ env.LOCATION }}001
        AKS_CLUSTER_NAME: ${{ env.PREFIX }}-aks-001
        TERRAFORM_STORAGE_ACCOUNT: ${{ env.PREFIX }}sttfstate${{ env.LOCATION }}001

    - name: Terraform Init
      run: pwsh -command "./scripts/Init-Terraform.ps1"

    - name: Terraform Plan
      run: pwsh -command "./scripts/Plan-Terraform.ps1"

    - name: Terraform Apply
      run: pwsh -command "./scripts/Apply-Terraform.ps1"

    - name: Terraform Destroy
      run: pwsh -command "./scripts/Destroy-Terraform.ps1"
      if: github.event.action == 'terraform-destroy'

    - name: Terraform Destroy
      run: pwsh -command "./scripts/Delete-Storage.ps1"
      if: github.event.action == 'delete-all'
