# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: Build environment

# name of GitHub event that triggers workflow
# https://help.github.com/en/actions/reference/events-that-trigger-workflows#watch-event-watch
on:
  # trigger when I star my own repo
  watch:
    types: [started]
  # trigger via webhook
  # https://github.com/adamrushuk/aks-nexus-velero/blob/master/TriggerCustomAction.ps1#L28
  repository_dispatch:
    types: [build]

# global environment variables
# https://help.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables
env:
  # prefix: used for some globally unique name requirements
  PREFIX: rush

  # debug
  CI_DEBUG: true

  # azure creds
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

  # other
  # prod or staging
  CERT_API_ENVIRONMENT: prod
  DNS_DOMAIN_NAME: nexus.thehypepipe.co.uk
  EMAIL_ADDRESS: adamrushuk+aksnexusvelero@gmail.com
  ENABLE_TLS_INGRESS: true
  FORCE_TEST_FAIL: false
  HAS_SUBDOMAIN: true
  LOCATION: uksouth
  # STORAGE_KEY: 'env var set by Get-StorageKey.ps1'

  # terraform
  TF_VERSION: "0.12.24" # "latest" is supported
  TF_WORKING_DIR: terraform

  # Env var concatenation is currently not supported at Workflow or Job scope. See workaround below:
  # https://github.community/t5/GitHub-Actions/How-can-we-concatenate-multiple-env-vars-at-workflow-and-job/td-p/48489

jobs:
  build:

    # always pin versions
    # view installed software: https://help.github.com/en/actions/reference/software-installed-on-github-hosted-runners
    runs-on: ubuntu-18.04

    # only run if owner triggered action
    if: github.actor == github.event.repository.owner.login

    steps:

    # Checkout
    # https://github.com/marketplace/actions/checkout
    - uses: actions/checkout@v2
      # specify different branch
      # NOT required as I've changed the default branch to develop
      # with:
      #   ref: develop

    # Env var concatenation
    # https://github.community/t5/GitHub-Actions/How-can-we-concatenate-multiple-env-vars-at-workflow-and-job/td-p/48489
    - name: Concatenate env vars (Workaround)
      run: |
        echo ::set-env name=AKS_RG_NAME::${{ env.PREFIX }}-rg-aks-dev-001
        echo ::set-env name=AKS_CLUSTER_NAME::${{ env.PREFIX }}-aks-001
        echo ::set-env name=TERRAFORM_STORAGE_ACCOUNT::${{ env.PREFIX }}sttfstate${{ env.LOCATION }}001
        echo ::set-env name=TERRAFORM_STORAGE_RG::${{ env.PREFIX }}-rg-tfstate-dev-001
        echo ::set-env name=VELERO_STORAGE_RG::${{ env.PREFIX }}-rg-velero-dev-001
        echo ::set-env name=VELERO_STORAGE_ACCOUNT::${{ env.PREFIX }}stbckuksouth001

    # Show event info
    - name: Show triggered event data
      run: pwsh -command "./scripts/Get-EventData.ps1"

    # Login
    - name: Login to Azure
      run: pwsh -command "./scripts/Login-Azure.ps1"


    # Prereqs
    - name: Create Storage Account for Terraform state
      run: pwsh -command "./scripts/Create-AzStorage.ps1"

    - name: Lookup Storage Key
      run: pwsh -command "./scripts/Get-StorageKey.ps1"

    - name: Replace tokens in Terraform config files
      run: pwsh -command "./scripts/Replace-Tokens.ps1"


    # # Terraform
    # - name: Terraform Init
    #   run: pwsh -command "./scripts/Invoke-Terraform.ps1 -Command 'init'"

    # - name: Terraform Plan
    #   run: pwsh -command "./scripts/Plan-Terraform.ps1"

    # - name: Terraform Apply
    #   run: pwsh -command "./scripts/Apply-Terraform.ps1"


    # https://github.com/hashicorp/terraform-github-actions#usage
    - name: Terraform Init
      uses: hashicorp/terraform-github-actions@v0.8.0
      with:
        tf_actions_subcommand: init
        tf_actions_version: ${{ env.TF_VERSION }}
        tf_actions_working_dir: ${{ env.TF_WORKING_DIR }}

    - name: Terraform Validate
      uses: hashicorp/terraform-github-actions@v0.8.0
      with:
        tf_actions_subcommand: validate
        tf_actions_version: ${{ env.TF_VERSION }}
        tf_actions_working_dir: ${{ env.TF_WORKING_DIR }}

    - name: Terraform Plan
      uses: hashicorp/terraform-github-actions@v0.8.0
      with:
        tf_actions_comment: true
        tf_actions_subcommand: plan
        tf_actions_version: ${{ env.TF_VERSION }}
        tf_actions_working_dir: ${{ env.TF_WORKING_DIR }}
      env:
        # (Optional) The GitHub API token used to post comments to pull requests.
        # Not required if the tf_actions_comment input is set to false
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Terraform Apply
      uses: hashicorp/terraform-github-actions@v0.8.0
      with:
        tf_actions_subcommand: apply
        tf_actions_version: ${{ env.TF_VERSION }}
        tf_actions_working_dir: ${{ env.TF_WORKING_DIR }}

    # # Helm - Init
    # # - name: Helm Init
    # #   run: pwsh -command "./scripts/Init-Helm.ps1"

    # # Kubernetes - Ingress
    # - name: Deploy Ingress Controller
    #   run: pwsh -command "./scripts/Deploy-Ingress-Controller.ps1"


    # # DNS
    # - name: Update DNS
    #   run: pwsh -command "./scripts/Update-Dns.ps1 -AksResourceGroupName ${{ env.AKS_RG_NAME }} -AksClusterName ${{ env.AKS_CLUSTER_NAME }} -DomainName ${{ env.DNS_DOMAIN_NAME }} -HasSubDomainName:\$${{ env.HAS_SUBDOMAIN }} -ApiKey ${{ secrets.API_KEY }} -ApiSecret ${{ secrets.API_SECRET }}"


    # # Kubernetes
    # # Cert-Manager
    # - name: Deploy cert-manager
    #   run: pwsh -command "./scripts/Deploy-Cert-Manager.ps1"

    # # Manifests
    # - name: Deploy kubernetes manifests
    #   run: pwsh -command "./scripts/Deploy-Manifests.ps1"

    # # Velero
    # - name: Deploy Velero
    #   run: pwsh -command "./velero/Deploy-Velero.ps1"
    #   env: # Or as an environment variable
    #     CREDENTIALS_VELERO: ${{ secrets.CREDENTIALS_VELERO }}


    # # Pester tests
    # - name: Run Pester tests
    #   run: pwsh -command "./scripts/Start-Test.ps1"

    # - name: Archive test artifacts
    #   if: always()
    #   uses: actions/upload-artifact@v1
    #   with:
    #     name: test results
    #     path: test/pester-test-results-junit.xml


    # Publish test results to https://www.check-run-reporter.com/
    # you should probably use a version tag (v1.0.2) instead of @master
    # WARNING: ALL env vars are passed to this Action Container
    # - uses: check-run-reporter/action@master
    #   if: always()
    #   env:
    #       CHECK_RUN_REPORTER_LABEL: 'Integration Tests'
    #       CHECK_RUN_REPORTER_REPORT: 'test/*-junit.xml'
    #       CHECK_RUN_REPORTER_TOKEN: ${{ secrets.CHECK_RUN_REPORTER_TOKEN }}

