name: Stop AKS Cluster

on:
  repository_dispatch:
    # name of GitHub event that triggers workflow
    types: [stop_aks_cluster]

  # enable manual workflow
  # https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#manually-running-a-workflow
  workflow_dispatch:
    inputs: {}

# global environment variables
env:
  # prefix: used for some globally unique name requirements
  PREFIX: rush

  # debug
  CI_DEBUG: true

  # azure creds
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  stop_aks_cluster:
    runs-on: ubuntu-18.04

    # only run if owner triggered action
    if: github.actor == github.event.repository.owner.login

    steps:
    # Checkout
    - uses: actions/checkout@v2
      # specify different branch
      # NOT required as I've changed the default branch to develop
      # with:
      #   ref: develop

    # Init tasks - inc env var concatenation
    - name: Init tasks - inc Env var concatenation (Workaround)
      run: |
        chmod -R +x ./scripts/
        echo "AKS_RG_NAME=${{ env.PREFIX }}-rg-aks-dev-001" >> $GITHUB_ENV
        echo "AKS_CLUSTER_NAME=${{ env.PREFIX }}-aks-001" >> $GITHUB_ENV
    # Show event info
    - name: Show triggered event data
      run: pwsh -command "./scripts/Get-EventData.ps1"
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}

    # Login
    - name: Login to Azure
      run: ./scripts/azure_login.sh

    # Stop
    # Prereqs: https://docs.microsoft.com/en-us/azure/aks/start-stop-cluster
    - name: Stop AKS Cluster
      run: ./scripts/stop_aks_cluster.sh

    # Notify
    - name: Notify slack
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      uses: pullreminders/slack-action@v1.0.9
      with:
        # env var concatenation not supported atm, so hard-code messages
        args: '{\"channel\":\"C012ZQHT9A4\",\"text\":\"[aks-nexus-velero] Stop AKS Cluster complete\"}'
