# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: Webhook

# name of GitHub event that triggers workflow
# https://help.github.com/en/actions/reference/events-that-trigger-workflows#external-events-repository_dispatch
# on: [repository_dispatch]

# it's possible to filter whole workflow using custom type sent, eg: from ValidateSet here:
# https://github.com/adamrushuk/github-actions/blob/master/TriggerCustomAction.ps1#L33
on:
  repository_dispatch:
    types: [test]

# global environment variables
# https://help.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables
env:
  MY_WORKFLOW_VAR: work

jobs:
  build:

    # always pin versions
    # # view installed software: https://help.github.com/en/actions/reference/software-installed-on-github-hosted-runners
    runs-on: windows-2019

    env:
      MY_JOB_VAR: job
      MY_WORK_JOB_VAR: ${{ env.MY_WORKFLOW_VAR }}-jobval01

    steps:
    # always run (as no if expression used)
    - name: Output event data
      env:
        MY_STEP_VAR: step
      run: |
        # Get event context data
        $eventContextJson = '${{ toJson( github.event ) }}'

        # Convert to PowerShell object
        $eventContext = $eventContextJson | ConvertFrom-Json

        # Output info
        Write-Output "action: $($eventContext.action)"
        Write-Output "client_payload: $($eventContext.client_payload)"

        # Env var concatenation
        Write-Output "MY_WORKFLOW_VAR is: [$env:MY_WORKFLOW_VAR]"
        Write-Output "MY_JOB_VAR is: [$env:MY_JOB_VAR]"
        Write-Output "MY_STEP_VAR is: [$env:MY_STEP_VAR]"
        Write-Output "MY_WORK_JOB_VAR is: [$env:MY_WORK_JOB_VAR]"
